### ISSUE TITLE
Automated tests with T2

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/zookeeper-operator-integration-tests#6]
The Zookeeper operator integration tests should be the first to run (nightly) in a T2-hosted cluster. The agent-integration-tests can act as a reference implementation here, although the actual tests will vary.

**Comment by maltesander** [comment]
There is still a problem with the zookeeper operator when scaling up or down (the integration tests will always fail). Its related to not updating configmaps (and or restarting pods when anything changes).
Either we fix that in the operator or leave it out for now?
